### ISSUE TITLE
Intermittent exception with no explicit separator

### ISSUE THREAD

**Issue by glowinthedark** [vot/xkpasswd-go#2]
Running the command without an explicit separator (e.g. without `-s .`) causes intermittent exceptions. 

Apparently, when the separator is not specified and a random function is used to generate the separator occasionally an empty string is generated which causes the exception below:

```bash
# xkpasswd-go
ginaling+avirse+pundis
# xkpasswd-go
stomaja=chnouscon=subbited
# xkpasswd-go
panic: runtime error: index out of range [7] with length 6

goroutine 1 [running]:
main.getSeparatorForComplexity(0x2, 0x720ac1d2b0, 0x63a830780)
        /data/data/com.termux/files/home/go/src/github.com/vot/xkpasswd-go/xkpasswd.go:97 +0xc0
main.main.func1(0x40000b0160, 0x63a6346f8, 0x0)
        /data/data/com.termux/files/home/go/src/github.com/vot/xkpasswd-go/xkpasswd.go:194 +0x118
github.com/urfave/cli.HandleAction(0x63a6e0bc0, 0x400008a4e0, 0x40000b0160, 0x40000b0160, 0x0)
        /data/data/com.termux/files/home/go/src/github.com/urfave/cli/app.go:523 +0xd0
github.com/urfave/cli.(*App).Run(0x400010e000, 0x40000881b0, 0x1, 0x1, 0x0, 0x0)
        /data/data/com.termux/files/home/go/src/github.com/urfave/cli/app.go:285 +0x410
main.main()
        /data/data/com.termux/files/home/go/src/github.com/vot/xkpasswd-go/xkpasswd.go:204 +0x3a0
```

The error is reproduceable on macos, Linux and Android (the stacktrace is from Android running under termux).

**Comment by vot** [comment]
Hi @glowinthedark,

Many thanks for raising both issues, I appreciate the feedback and details you provided.

I just fixed this issue in this commit:
https://github.com/vot/xkpasswd-go/commit/ccaef3da7c7bc3db7c9e22dc6071a428d36b37e3

Basically I used random number generation with limit of `9` - worked fine for digit generation but the index could be larger than the amount of separators.

Now that's based on the actual number of available separators.
Let me know if this fixes it for you.

Vot

**Comment by glowinthedark** [comment]
@vot: I think I installed the last working build with `go get -u -v github.com/vot/xkpasswd-go` — I run this again which should supposedly pull the latest commits. The command completes successfully but I do not see the binary under `$GOPATH/bin/xkpasswd-go`.

Also tried cloning and building with `go build xkpasswd.go` — completes successfully but no binary is generated either.

**Update**: apparently this was caused by the package name. After renaming the package to `main` the binary is generated as expected. 

```patch
git diff xkpasswd.go
diff --git a/xkpasswd.go b/xkpasswd.go
index b329f85..a413a34 100644
--- a/xkpasswd.go
+++ b/xkpasswd.go
@@ -1,4 +1,4 @@
-package xkpasswd
+package main

 import "fmt"
 import "log"
```

Also confirming that the exception is now not thrown when no explicit separator is defined.

**Comment by vot** [comment]
Hi @glowinthedark - thanks for pointing that out.
I went a little bit too far with clean up and wanted to namespace the package. I ran into some dependency issues on my end which prevented me from testing this sufficiently - sorry about inconvenience.

I now reverted that change so it should be building fine.

Thanks for confirming the bug is fixed and for raising it in the first place 👍
